AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: husky_shelter
  AnimalImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: animalimagesbucket
  WebsiteAdoptionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: websiteadoptionbucket
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront Origin Identity for Husky Shelter
  WebsiteAdoptionBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: websiteadoptionbucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              Fn::Sub: arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity
                ${CloudFrontOriginIdentity}
          Action: s3:GetObject
          Resource: arn:aws:s3:::websiteadoptionbucket/*
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName:
            Fn::GetAtt:
            - WebsiteAdoptionBucket
            - DomainName
          Id: websiteadoptionid
          S3OriginConfig:
            OriginAccessIdentity:
              Fn::Sub: origin-access-identity/cloudfront/${CloudFrontOriginIdentity}
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: websiteadoptionid
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
Outputs:
  S3ImagesBucketName:
    Description: BucketName
    Value:
      Ref: AnimalImagesBucket
  S3WebsiteAdoptionBucketName:
    Description: BucketName
    Value:
      Ref: WebsiteAdoptionBucket
  S3WebsiteAdoptionBucketURL:
    Description: BucketURL
    Value:
      Fn::GetAtt:
      - WebsiteAdoptionBucket
      - WebsiteURL
