AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  HuskySheltersAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: aws
      Name: husky-shelters-api
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: swaggerFile.yaml
      
  UpdateItem:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-item-husky-shelters
      Handler: app.update_item
      Runtime: python3.9
      CodeUri: build
      Events:
        UpdateItem:
          Type: Api
          Properties:
            RestApiId: !Ref HuskySheltersAPI
            Path: "/update-item"
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
  GetTableItems:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-table-items-husky-shelters
      Handler: app.get_table_items
      Runtime: python3.9
      CodeUri: build
      Events:
        GetTableItems:
          Type: Api
          Properties:
            RestApiId: !Ref HuskySheltersAPI
            Path: "/table-items"
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
       
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

      TableName: "husky_shelter"

  AnimalImagesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: animalimagesbucket

Outputs:
  S3BucketName:
    Description: BucketName
    Value: !Ref AnimalImagesBucket      



