AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  HuskySheltersAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: aws
      Name: husky-shelters-api
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: swaggerFile.yaml


  UpdateItem:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: update-item-husky-shelters
      Handler: app.update_item
      Runtime: python3.7
      CodeUri: build
      Events:
        UpdateItem:
          Type: Api
          Properties:
            RestApiId: !Ref HuskySheltersAPI
            Path: "/update-item"
            Method: POST
      Policies:
        - DynamoDBWritePolicy: 
            TableName: !Ref Table
  GetTableItems:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-table-items-husky-shelters
      Handler: app.get_table_items
      Runtime: python3.7
      CodeUri: build
      Events:
        GetTableItems:
          Type: Api
          Properties:
            RestApiId: !Ref HuskySheltersAPI
            Path: "/get-table-items"
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
  GetImagesByID:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-images-by-id-husky-shelters
      Handler: app.get_images_by_id
      Runtime: python3.7
      CodeUri: build
      Events:
        GetImagesByID:
          Type: Api
          Properties:
            RestApiId: !Ref HuskySheltersAPI
            Path: "/get-images/{id}"
            Method: GET
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AnimalImagesBucket
  UploadImageByID:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: upload-image-by-id-husky-shelters
      Handler: api.upload_image_by_id
      Runtime: nodejs14.x
      CodeUri: src
      Events:
        UploadImageByID:
          Type: Api
          Properties:
            RestApiId: !Ref HuskySheltersAPI
            Path: "/upload-image/{id}"
            Method: GET
      Policies:
        - S3WritePolicy:
            BucketName: !Ref AnimalImagesBucket
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
       
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

      TableName: "husky_shelter"

  AnimalImagesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: animalimagesbucket
      AccessControl: 'Private'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - "*"
                     

            
            
            


  WebsiteAdoptionBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: websiteadoptionbucket
      WebsiteConfiguration:
        ErrorDocument: 'index.html'
        IndexDocument: 'index.html'

  AnimalDataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: animaldatabucket346253

  ExcelProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.excel_processing_handler
      Runtime: python3.7
      CodeUri: build
      Events:
        ProcessExcel:
          Type: S3
          Properties:
            Bucket:
              Ref: "AnimalDataBucket"
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".csv" 
      Policies:
        - S3ReadPolicy:
            BucketName: 'animaldatabucket346253'
        - DynamoDBCrudPolicy:
            TableName: 'husky_shelter'

  S3ImagesConversion:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3-images-conversion-husky-shelters
      Handler: app.s3_images_handler
      Runtime: python3.7
      CodeUri: build
      Events:
        ConverImages:
          Type: S3
          Properties:
            Bucket:
              Ref: "AnimalImagesBucket"
            Events: s3:ObjectCreated:*
      Policies:
        - S3CrudPolicy:
            BucketName: 'animalimagesbucket'

  CloudFrontOriginIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'CloudFront Origin Identity for Husky Shelter'

  WebsiteAdoptionBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: websiteadoptionbucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
            Action: 's3:GetObject'
            Resource: 'arn:aws:s3:::websiteadoptionbucket/*'

  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteAdoptionBucket.DomainName
            Id: websiteadoptionid
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
        Enabled: true
        DefaultRootObject: 'index.html'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: websiteadoptionid
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: 'none'
          ViewerProtocolPolicy: 'redirect-to-https'
        ViewerCertificate:
          CloudFrontDefaultCertificate: true      
          
Outputs:
  S3ImagesBucketName:
    Description: BucketName
    Value: !Ref AnimalImagesBucket      

  S3WebsiteAdoptionBucketName:
    Description: BucketName
    Value: !Ref WebsiteAdoptionBucket  

  S3DataBucketName:
    Description: BucketName
    Value: !Ref AnimalDataBucket  

  S3WebsiteAdoptionBucketURL:
    Description: BucketURL
    Value: !GetAtt WebsiteAdoptionBucket.WebsiteURL  



