AWSTemplateFormatVersion: "2010-09-09"
<<<<<<< HEAD
Transform: AWS::Serverless-2016-10-31

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"

        -
          AttributeName: "health"
          AttributeType: "S"

        -
          AttributeName: "status"
          AttributeType: "S"

        -
          AttributeName: "age"
          AttributeType: "N"

        -
          AttributeName: "location"
          AttributeType: "S"

        -
          AttributeName: "image_collection_id"
          AttributeType: "S"


      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
       
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

      TableName: "husky_shelter"      
=======
Transform: AWS::Serverless-2016-10-31
>>>>>>> origin/main
